export const tariffs = [
  { name: 'HomeWifi' },
  { name: 'HomeFree' },
  { name: 'HomeOptical' },
  { name: 'Fresh' },
]

export const homeFree = [
  {
    title: 'HomeFree-1',
    price: '50.000',
    speedAfter1: '10 Mbit/s',
    speedAfter20: '5 Mbit/s',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '11',
    limit: 'Cheksiz',
  },
  {
    title: 'HomeFree-2',
    price: '85.000',
    speedAfter1: '25 Mbit/s',
    speedAfter20: '8 Mbit/s',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '11',
    limit: 'Cheksiz',
  },
  {
    title: 'HomeFree-3',
    price: '100.000',
    speedAfter1: '200 Mbit/s',
    speedAfter20: '15 Mbit/s',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '11',
    limit: 'Cheksiz',
  },
  {
    title: 'HomeFree-4',
    price: '130.000',
    speedAfter1: '200 Mbit/s',
    speedAfter20: '25 Mbit/s',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '70',
    limit: 'Cheksiz',
  },
  {
    title: 'HomeFree-5',
    price: '180.000',
    speedAfter1: '200 Mbit/s',
    speedAfter20: '50 Mbit/s',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '70',
    limit: 'Cheksiz',
  },
  {
    title: 'HomeFree-6',
    price: '250.000',
    speedAfter1: '200 Mbit/s',
    speedAfter20: '100 Mbit/s',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '70',
    limit: 'Cheksiz',
  },
  {
    title: 'HomeFree-7G',
    price: '300.000',
    speedAfter1: '200 Mbit/s',
    speedAfter20: '200 Mbit/s',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '70',
    limit: 'Cheksiz',
    newBadge: true,
  },
  {
    title: 'HomeFree-8G',
    price: '450.000',
    speedAfter1: '300 Mbit/s',
    speedAfter20: '300 Mbit/s',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '70',
    limit: 'Cheksiz',
    newBadge: true,
  },
]

export const homeWifi = [
  {
    title: 'HomeWifi-1',
    price: '80.000',
    speedAfter1: '10 Mbit/s',
    speedAfter20: '5 Mbit/s',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '11',
    limit: 'Cheksiz',
  },
  {
    title: 'HomeWifi-2',
    price: '120.000',
    speedAfter1: '25 Mbit/s',
    speedAfter20: '12 Mbit/s',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '11',
    limit: 'Cheksiz',
  },
  {
    title: 'HomeWifi-3',
    price: '150.000',
    speedAfter1: '200 Mbit/s',
    speedAfter20: '25 Mbit/s',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '70',
    limit: 'Cheksiz',
  },
  {
    title: 'HomeWifi-4',
    price: '180.000',
    speedAfter1: '200 Mbit/s',
    speedAfter20: '40 Mbit/s',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '70',
    limit: 'Cheksiz',
  },
  {
    title: 'HomeWifi-5',
    price: '230.000',
    speedAfter1: '200 Mbit/s',
    speedAfter20: '50 Mbit/s',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '70',
    limit: 'Cheksiz',
  },
  {
    title: 'HomeWifi-6',
    price: '300.000',
    speedAfter1: '200 Mbit/s',
    speedAfter20: '100 Mbit/s',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '70',
    limit: 'Cheksiz',
  },
  {
    title: 'HomeWifi-7G',
    price: '350.000',
    speedAfter1: '200 Mbit/s',
    speedAfter20: '200 Mbit/s',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '70',
    limit: 'Cheksiz',
    newBadge: true,
  },
  {
    title: 'HomeWifi-8G',
    price: '500.000',
    speedAfter1: '300 Mbit/s',
    speedAfter20: '300 Mbit/s',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '70',
    limit: 'Cheksiz',
    newBadge: true,
  },
]

export const homeOptical = [
  {
    title: 'HomeOptical',
    price: '10.000',
    speed: '10 Mbit/s',
    priceForOneMb: "0.2 so'm",
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '11',
  },
  {
    title: 'HomeOpticalVIP',
    price: '20.000',
    speed: '100 Mbit/s',
    priceForOneMb: "0.2 so'm",
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '11',
  },
]

export const fresh = [
  {
    title: 'Ikki kishilik',
    price: '49.999',
    speed: 'Cheksiz',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '11',
    limit: 'Cheksiz',
  },
  {
    title: 'Besh kishilik',
    price: '149.999',
    speed: 'Cheksiz',
    tasix: 'Tekin',
    istv: '1 Gbit/s',
    iptv: '11',
    limit: 'Cheksiz',
  },
]
